# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Marle_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  Marle_config = release
  Sandbox_config = release

else ifeq ($(config),dist)
  Marle_config = dist
  Sandbox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Marle Sandbox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Marle:
ifneq (,$(Marle_config))
	@echo "==== Building Marle ($(Marle_config)) ===="
	@${MAKE} --no-print-directory -C Marle -f Makefile config=$(Marle_config)
endif

Sandbox: Marle
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Marle -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Marle"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"